In [5]:
import yaml
import pickle
from fastai.vision.all import *
from pathlib import Path

with open('params.yaml') as file:
    params = yaml.safe_load(file)

data = params['data']

with open(Path('model_resnet18_fas-fine-tune5.pkl'), 'rb') as f:
    learn = pickle.load(f)

In [6]:
def get_preds(file_size, pat_str, reorder_):
    files = get_image_files(Path(pat_str))
    dl = learn.dls.test_dl(files[:file_size])
    preds = learn.get_preds(dl=dl, with_decoded=True, reorder=reorder_) # If with_decoded=True
    return preds

In [8]:
pat_str = data['test_mels']
files = get_image_files(Path(pat_str))
dl = learn.dls.test_dl(files)
preds = learn.get_preds(dl=dl, with_decoded=True, reorder=False)

Code:
``` python 
valid_preds = learn.get_preds()
valid_preds
```
Output:
``` bash
(tensor([[1.0939e-05, 9.9999e-01],
         [1.8558e-07, 1.0000e+00],
         [9.9998e-01, 2.2818e-05],
         ...,
         [9.9999e-01, 7.9484e-06],
         [9.9919e-01, 8.0834e-04],
         [9.9999e-01, 5.9491e-06]]),
 tensor([1, 1, 0,  ..., 0, 0, 0]))
```


In [22]:
test_preds = preds[2]
test_preds_ndarray = test_preds.numpy()

In [29]:
file_name_list = [f.stem for f in files]

In [39]:
outpu_str = ''
for f, p in zip(file_name_list, test_preds_ndarray):
    res = f + '\\' + str(p) + '\n'
    outpu_str += res
    
with open(Path('ouput_res_resnet18_fas_fine_tune5.txt'), 'w') as f:
    f.write(outpu_str)

In [17]:
files = get_image_files(Path(data['test_mels']))
dl = learn.dls.test_dl(files[:10])
dl

In [21]:
preds = learn.get_preds(dl=dl, with_decoded=True)
preds

(tensor([[1.2987e-04, 9.9987e-01],
         [1.2971e-10, 1.0000e+00],
         [2.6153e-07, 1.0000e+00],
         [2.0232e-07, 1.0000e+00],
         [9.4511e-01, 5.4891e-02],
         [2.9987e-07, 1.0000e+00],
         [9.9315e-01, 6.8503e-03],
         [9.3358e-01, 6.6417e-02],
         [2.4884e-07, 1.0000e+00],
         [1.8370e-03, 9.9816e-01]]),
 None,
 tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 1]))