In [4]:
import yaml
import pickle
from mllib.utils.pkl import load_data_from_pkl
from pathlib import Path
from mllib.utils.dvc import load_params

params = load_params()

data = params['data']
model_path = Path(params['train']['model'])

model = load_data_from_pkl(model_path)
get_simple_summary(model)

Layer (type (var_name))                  Input Shape          Output Shape         Param #              Trainable
ResNet (ResNet)                          [24, 3, 100, 100]    [24, 1000]           --                   True
├─Conv2d (conv1)                         [24, 3, 100, 100]    [24, 64, 50, 50]     9,408                True
├─BatchNorm2d (bn1)                      [24, 64, 50, 50]     [24, 64, 50, 50]     128                  True
├─ReLU (relu)                            [24, 64, 50, 50]     [24, 64, 50, 50]     --                   --
├─MaxPool2d (maxpool)                    [24, 64, 50, 50]     [24, 64, 25, 25]     --                   --
├─Sequential (layer1)                    [24, 64, 25, 25]     [24, 64, 25, 25]     --                   True
│    └─BasicBlock (0)                    [24, 64, 25, 25]     [24, 64, 25, 25]     --                   True
│    │    └─Conv2d (conv1)               [24, 64, 25, 25]     [24, 64, 25, 25]     36,864               True
│    │    └─BatchN

In [2]:
%load_ext autoreload
%autoreload 2

from src.train.models import torch_models, get_torch_model
from mllib.pytorch.utils import get_simple_summary
from mllib.utils.dvc import load_params
import torch

params = load_params()
device = "cuda" if torch.cuda.is_available() else "cpu"
model = get_torch_model(params=params, device=device)

get_simple_summary(model)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Layer (type (var_name))                  Input Shape          Output Shape         Param #              Trainable
ResNet (ResNet)                          [24, 3, 100, 100]    [24, 2]              --                   True
├─Conv2d (conv1)                         [24, 3, 100, 100]    [24, 64, 50, 50]     9,408                True
├─BatchNorm2d (bn1)                      [24, 64, 50, 50]     [24, 64, 50, 50]     128                  True
├─ReLU (relu)                            [24, 64, 50, 50]     [24, 64, 50, 50]     --                   --
├─MaxPool2d (maxpool)                    [24, 64, 50, 50]     [24, 64, 25, 25]     --                   --
├─Sequential (layer1)                    [24, 64, 25, 25]     [24, 64, 25, 25]     --                   True
│    └─BasicBlock (0)                    [24, 64, 25, 25]     [24, 64, 25, 25]     --                   True
│    │    └─Conv2d (conv1)               [24, 64, 25, 25]     [24, 64, 25, 25]     36,864               True
│    │    └─BatchN

In [ ]:
model.

In [16]:
import torchvision

weights = torchvision.models.EfficientNet_B0_Weights.DEFAULT # .DEFAULT = best available weights 
model_0 = torchvision.models.efficientnet_b0(weights=weights).to('cpu')

get_simple_summary(model=model_0, input_shape=(24, 3, 64, 64))

Layer (type (var_name))                                      Input Shape          Output Shape         Param #              Trainable
EfficientNet (EfficientNet)                                  [24, 3, 64, 64]      [24, 1000]           --                   True
├─Sequential (features)                                      [24, 3, 64, 64]      [24, 1280, 2, 2]     --                   True
│    └─Conv2dNormActivation (0)                              [24, 3, 64, 64]      [24, 32, 32, 32]     --                   True
│    │    └─Conv2d (0)                                       [24, 3, 64, 64]      [24, 32, 32, 32]     864                  True
│    │    └─BatchNorm2d (1)                                  [24, 32, 32, 32]     [24, 32, 32, 32]     64                   True
│    │    └─SiLU (2)                                         [24, 32, 32, 32]     [24, 32, 32, 32]     --                   --
│    └─Sequential (1)                                        [24, 32, 32, 32]     [24, 16, 32,

In [6]:
def get_preds(file_size, pat_str, reorder_):
    files = get_image_files(Path(pat_str))
    dl = learn.dls.test_dl(files[:file_size])
    preds = learn.get_preds(dl=dl, with_decoded=True, reorder=reorder_) # If with_decoded=True
    return preds

In [8]:
pat_str = data['test_mels']
files = get_image_files(Path(pat_str))
dl = learn.dls.test_dl(files)
preds = learn.get_preds(dl=dl, with_decoded=True, reorder=False)

Code:
``` python 
valid_preds = learn.get_preds()
valid_preds
```
Output:
``` bash
(tensor([[1.0939e-05, 9.9999e-01],
         [1.8558e-07, 1.0000e+00],
         [9.9998e-01, 2.2818e-05],
         ...,
         [9.9999e-01, 7.9484e-06],
         [9.9919e-01, 8.0834e-04],
         [9.9999e-01, 5.9491e-06]]),
 tensor([1, 1, 0,  ..., 0, 0, 0]))
```


In [22]:
test_preds = preds[2]
test_preds_ndarray = test_preds.numpy()

In [29]:
file_name_list = [f.stem for f in files]

In [39]:
outpu_str = ''
for f, p in zip(file_name_list, test_preds_ndarray):
    res = f + '\\' + str(p) + '\n'
    outpu_str += res
    
with open(Path('ouput_res_resnet18_fas_fine_tune5.txt'), 'w') as f:
    f.write(outpu_str)

In [17]:
files = get_image_files(Path(data['test_mels']))
dl = learn.dls.test_dl(files[:10])
dl

In [21]:
preds = learn.get_preds(dl=dl, with_decoded=True)
preds

(tensor([[1.2987e-04, 9.9987e-01],
         [1.2971e-10, 1.0000e+00],
         [2.6153e-07, 1.0000e+00],
         [2.0232e-07, 1.0000e+00],
         [9.4511e-01, 5.4891e-02],
         [2.9987e-07, 1.0000e+00],
         [9.9315e-01, 6.8503e-03],
         [9.3358e-01, 6.6417e-02],
         [2.4884e-07, 1.0000e+00],
         [1.8370e-03, 9.9816e-01]]),
 None,
 tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 1]))